# -*- coding: utf-8 -*-
"""Panchal_1226051_Project 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlAi0eve8JV9D1zgtICqhtM10wTBauqw
"""

with open('requirements.txt', 'w') as f:
    f.write('''flask
langchain
transformers
pdf2image
PyPDF2
pytesseract
faiss-cpu
tiktoken
chromadb
''')

with open('Procfile', 'w') as f:
    f.write('web: python app.py')

"""# What is this Project about?
- This project is an interactive chatbot application powered by a large language model (LLM) for document-based question answering. The main goal was to create a tool that allows users to upload PDF documents and interactively ask questions about the content, leveraging advanced natural language processing techniques.
- The workflow is explained at the end, outlining how it works.

# Setting up the Environment
"""



import pytesseract
from PIL import Image
from pdf2image import convert_from_path
import PyPDF2
from transformers import pipeline
from google.colab import files
import io

"""# Function to Extract Text from PDFs

"""

# Function to extract text from a PDF (with OCR support for scanned PDFs)
def extract_text_from_pdf(pdf_path, use_ocr=False):
    text = ""
    if use_ocr:
        # Convert PDF pages to images
        images = convert_from_path(pdf_path)
        for image in images:
            # Use Tesseract OCR to extract text from the image
            text += pytesseract.image_to_string(image)
    else:
        # Extract text from text-based PDFs
        with open(pdf_path, "rb") as file:
            pdf_reader = PyPDF2.PdfReader(file)
            for page in pdf_reader.pages:
                text += page.extract_text()

    return text

"""# Function to Answer Questions"""

# Function to answer questions using a QA model and enhanced prompt engineering
def answer_question(context, question, qa_model):
    # Example of a more structured prompt
    prompt = f"Based on the following text, answer the question in detail.\n\nContext: {context}\n\nQuestion: {question}\nAnswer:"

    # Use the model to get the answer
    return qa_model({"question": question, "context": context})["answer"]

"""# An Interactive Chatbot

"""

# Interactive Chatbot with PDF Upload and Question Answering
def interactive_chatbot():
    # Upload PDF file using Google Colab's file upload widget
    uploaded = files.upload()

    if uploaded:
        # Get the uploaded PDF file name
        pdf_file = next(iter(uploaded))
        print(f"PDF file '{pdf_file}' uploaded successfully!")

        # Load the Hugging Face QA model
        qa_model = pipeline("question-answering", model="deepset/roberta-base-squad2")

        # Extract text from the uploaded PDF
        text = extract_text_from_pdf(pdf_file, use_ocr=True)  # Use OCR for scanned PDFs

        print("Chatbot is ready! Ask me anything from the document!")

        while True:
            user_question = input("You: ")

            if user_question.lower() in ["exit", "quit", "bye"]:
                print("Chatbot: Goodbye! Exiting...")
                break

            # Get the answer from the model using the enhanced prompt
            answer = answer_question(text, user_question, qa_model)
            print(f"Chatbot: {answer}")
    else:
        print("No PDF file uploaded!")


"""# Running the Chatbot"""

# Run the chatbot
if __name__ == "__main__":
    interactive_chatbot()

"""# Workflow

## 1. Text Extraction from PDFs:
- The application can handle both text-based and scanned PDFs. It uses PyPDF2 to directly extract text from standard PDFs and Tesseract OCR to process scanned documents, ensuring flexibility across different file types.

## 2. Question Answering with LLM:
- I am using a pretrained Hugging Face model (deepset/roberta-base-squad2) to answer questions based on the extracted text. Prompt engineering ensures the model provides accurate, detailed, and context-aware answers.

## 3. Interactive Chatbot:
The core of the project is the interactive chatbot interface. Users can:

* Upload a PDF document.
* Ask questions about its content in natural language.
* Receive precise answers based on the document's context.

# Conclusion:
- In conclusion, this project successfully demonstrates the power of large language models (LLMs) in creating an interactive chatbot that answers questions from PDF documents. By combining text extraction, OCR, and question-answering techniques, it offers a user-friendly experience without requiring technical expertise. The project also lays a strong foundation for future improvements, showcasing how scalable and adaptable LLMs can be for document understanding and more complex applications. Overall, it highlights the practical potential of LLMs in solving real-world problems.
"""
